### ISSUE TITLE
Support for Data Dogs new log managment?

### ISSUE THREAD

**Issue by haggerty-william** [serilog/serilog-sinks-datadog#10]
Are there plans to support Data dog as a log server instead of using it just as an event system?

FYI: [https://www.datadoghq.com/log-management/](https://www.datadoghq.com/log-management/)

**Comment by egorchabala** [comment]
+1 to have Serilog integration with Datadog Log Management. Since they acquired Loggly, I think the following sink may be considered as good starting point - https://github.com/serilog/serilog-sinks-loggly

**Comment by CumpsD** [comment]
Apparently you can just use https://github.com/pauldambra/Serilog.Sinks.Network for the new log stuff.

```
"WriteTo": [
      {
        "Name": "UDPSink", "Args": { "uri": "http://127.0.0.1", "port": "10125" }
      }
    ],
```

and

```
init_config: 

instances: 
    [{}]

#Log section
logs: 
   - type: udp
     port: 10125
     service: some-serilog-yaml
     source: some-datadog-docker
     sourcecategory: some-datadog-publicservices
     tags: some-datadog-tag1
```
